package trabalho_ds;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USUARIO
 */
public class frmListarFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form frmListarCliente
     */
    public frmListarFornecedor() {
        initComponents();
        mostarValores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();
        btnMostarCampos = new javax.swing.JButton();
        btnCarregaFormulario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaFornecedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelaFornecedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "CPF", "RG", "Telefone","Email","CEP","Cidade","Estado","Rua","Numero"
            }
        ));
        jScrollPane1.setViewportView(tabelaFornecedor);

        btnMostarCampos.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Etec\\Modulo 2\\Desenvolvimento de Sistemas\\icon\\pesquisa.png")); // NOI18N
        btnMostarCampos.setText("Pesquisar");
        btnMostarCampos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMostarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarCamposActionPerformed(evt);
            }
        });

        btnCarregaFormulario.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Etec\\Modulo 2\\Desenvolvimento de Sistemas\\icon\\carregando.png")); // NOI18N
        btnCarregaFormulario.setText("Carregar no Formulario");
        btnCarregaFormulario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCarregaFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarregaFormularioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1031, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnMostarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCarregaFormulario, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCarregaFormulario, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(btnMostarCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarCamposActionPerformed
      
        
        mostarValores();
        
        
    }//GEN-LAST:event_btnMostarCamposActionPerformed

    private void btnCarregaFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarregaFormularioActionPerformed
       
        
        carregarCampos();
        
        
    }//GEN-LAST:event_btnCarregaFormularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmListarFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarregaFormulario;
    private javax.swing.JButton btnMostarCampos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFornecedor;
    // End of variables declaration//GEN-END:variables

  private void mostarValores() {

        try {
            fornecedorDAO objfornecedordao = new fornecedorDAO();
            
            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<fornecedorDTO> lista = objfornecedordao.PesquisarFornecedor();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getNome(),
                    lista.get(num).getCpf(),
                    lista.get(num).getRg(),
                    lista.get(num).getEmail(),
                    lista.get(num).getTelefone(), 
                    lista.get(num).getCep(),
                    lista.get(num).getEstado(),
                    lista.get(num).getCidade(),
                    lista.get(num).getRua(),
                    lista.get(num).getNumero()
                });

            }

        } catch (SQLException erro) {

            JOptionPane.showMessageDialog(null, "Listar Valores VIEW:" + erro);

        }

    }


    private void carregarCampos(){
  
         int setar =  tabelaFornecedor.getSelectedRow();
        
        frmFornecedor.txtCod.setText(tabelaFornecedor.getModel().getValueAt(setar, 0).toString());
        frmFornecedor.txtNome.setText(tabelaFornecedor.getModel().getValueAt(setar, 1).toString());
        frmFornecedor.txtCPF.setText(tabelaFornecedor.getModel().getValueAt(setar, 2).toString());
        frmFornecedor.txtRG.setText(tabelaFornecedor.getModel().getValueAt(setar, 3).toString());
        frmFornecedor.txtEmail.setText(tabelaFornecedor.getModel().getValueAt(setar, 4).toString());
        frmFornecedor.txtTelefone.setText(tabelaFornecedor.getModel().getValueAt(setar, 5).toString());
        frmFornecedor.txtCEP.setText(tabelaFornecedor.getModel().getValueAt(setar, 6).toString());
        frmFornecedor.txtCidade.setText(tabelaFornecedor.getModel().getValueAt(setar, 7).toString());
        frmFornecedor.txtEstado.setText(tabelaFornecedor.getModel().getValueAt(setar, 8).toString());
        frmFornecedor.txtRua.setText(tabelaFornecedor.getModel().getValueAt(setar, 9).toString());        
        frmFornecedor.txtNumero.setText(tabelaFornecedor.getModel().getValueAt(setar, 10).toString());
        
  
        
        
  
    }









}
